spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-208-74-199.compute-1.amazonaws.com/daljav51hvnuk1
  username: jzaidtqhhjazbh
  password: bb16a0c6c761e8d4062c7b50dbf3097c63c974dabc60bbc836bdd9781d2efab7
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis.url: redis://:pd0c1d2a799aa9143b7584af703e71f095f689b62490a37c269cea0b1f47ea56e@ec2-54-167-87-126.compute-1.amazonaws.com:29459