spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-208-74-199.compute-1.amazonaws.com/daljav51hvnuk1
  username: jzaidtqhhjazbh
  password: bb16a0c6c761e8d4062c7b50dbf3097c63c974dabc60bbc836bdd9781d2efab7
  platform: postgres
  driver-class-name: org.postgresql.Driver
